// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCq4HnUi4Ks_FYmj40oKD-lwjZRLgW8XVk',
    appId: '1:948516696549:web:a9f62ec16fe474bc80ff0c',
    messagingSenderId: '948516696549',
    projectId: 'smartsafeapp-a4d20',
    authDomain: 'smartsafeapp-a4d20.firebaseapp.com',
    storageBucket: 'smartsafeapp-a4d20.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxpxdYNiC-RpML-M9QeGW9d_azMC6RPNI',
    appId: '1:948516696549:android:85ab8667cdd5f9c180ff0c',
    messagingSenderId: '948516696549',
    projectId: 'smartsafeapp-a4d20',
    storageBucket: 'smartsafeapp-a4d20.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9ByW3lkjBXO36S2qHA87A1o701aPSfLU',
    appId: '1:948516696549:ios:30db7e2cb97db6f780ff0c',
    messagingSenderId: '948516696549',
    projectId: 'smartsafeapp-a4d20',
    storageBucket: 'smartsafeapp-a4d20.firebasestorage.app',
    iosBundleId: 'com.example.smartSafeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9ByW3lkjBXO36S2qHA87A1o701aPSfLU',
    appId: '1:948516696549:ios:30db7e2cb97db6f780ff0c',
    messagingSenderId: '948516696549',
    projectId: 'smartsafeapp-a4d20',
    storageBucket: 'smartsafeapp-a4d20.firebasestorage.app',
    iosBundleId: 'com.example.smartSafeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCq4HnUi4Ks_FYmj40oKD-lwjZRLgW8XVk',
    appId: '1:948516696549:web:a874856c22d944e980ff0c',
    messagingSenderId: '948516696549',
    projectId: 'smartsafeapp-a4d20',
    authDomain: 'smartsafeapp-a4d20.firebaseapp.com',
    storageBucket: 'smartsafeapp-a4d20.firebasestorage.app',
  );
}
